version: '3.6'

services:
  db:
    image: postgres
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: exnation
    expose:
      - 54325
    ports:
      - 127.0.0.1:54325:5432

  app:
    build:
      context: packages/client
    ports:
      - "8080:8080"
